export const ZENITH_MODELS = [
  {
    id: 'zenith-mikel',
    name: 'Mikel',
    apiModel: 'claude-opus-5-thinking',
    provider: 'tabitoken',
    description: 'Flagship deep reasoning and complex coding (Opus 5)',
    badge: 'Recommended',
    contextWindow: '200k',
    speed: 'Deep',
    reasoning: 'Maximum',
    icon: 'Sparkles',
    default: true,
  },
  {
    id: 'zenith-charles',
    name: 'Charles',
    apiModel: 'claude-opus-4-8-thinking',
    provider: 'tabitoken',
    description: 'High-precision advanced reasoning engine (Opus 4.8)',
    badge: 'Precision',
    contextWindow: '128k',
    speed: 'High',
    reasoning: 'Exceptional',
    icon: 'Brain',
    default: false,
  },
  {
    id: 'zenith-jerald',
    name: 'Jerald',
    apiModel: 'deepseek-v4-flash',
    provider: 'agentrouter',
    description: 'DeepSeek V4 Flash — fast reasoning & coding (AgentRouter)',
    badge: 'Balanced',
    contextWindow: '128k',
    speed: 'Fast',
    reasoning: 'High',
    icon: 'Sparkles',
    default: false,
  },
  {
    id: 'zenith-riezl',
    name: 'Riezl',
    apiModel: 'gpt-5.6-sol',
    provider: 'agentrouter',
    description: 'GPT-5.6 Sol — ultra-fast everyday AI (AgentRouter)',
    badge: 'Ultra Fast',
    contextWindow: '128k',
    speed: 'Instant',
    reasoning: 'Balanced',
    icon: 'Zap',
    default: false,
  },
];

export const getModelById = (id) => {
  return ZENITH_MODELS.find((m) => m.id === id) || ZENITH_MODELS[0];
};
